### PR TITLE
Gl3 polygon mode fix

### PR DESCRIPTION
**Pull request by tobias-dv-lnu**

### CODE REVIEW

**Comment by tobias-dv-lnu** [comment]
This seems to increase stability on osx, still not perfect though...

**Comment by elect86** [comment]
Which kind of instabilities have you experienced?

**Comment by elect86** [comment]
Any crash log? What's the complete error code exactly?

It doesn't make sense, because `glGetInteger` does exactly that behind the curtains..

**Comment by Sylvyrfysh** [comment]
Signal 134 is SIGABRT, which means something from macOS decided to kill it.
This typically happens with accesses to camera or something else inside the
app. I have no clue what could be causing this, simply put

**Comment by tobias-dv-lnu** [comment]
Yes, glGetInteger does basically the same thing. However, GL_POLYGON_MODE returns two values , according to the GL documentation, as glGetInteger allocates only room for one value and then uses nglGetIntegerv, there is potential for trouble with memory.

**Comment by elect86** [comment]
Uh, you are right..!

Would you switch it to `POLYGON_MODE -> glGetVec2i(GL_POLYGON_MODE)[0]` then?

**Comment by tobias-dv-lnu** [comment]
yes, glGetVec2i seems to work just as well on osx :)

**Comment by elect86** [comment]
Thanks tobias!

**Comment by elect86** [comment]
> demo (and my own application) crashes/exits with error-code 134, about 50% of starts often after a few frames are rendered on osx. With this fix this seems to be less frequent.

Do you still get crashes though?

**Comment by elect86** [comment]
that was a nice catch though @tobias-dv-lnu

**Comment by tobias-dv-lnu** [comment]
actually there seem to be no crashes on startup of the demo right now. However, memory-related stuff is tricky and behaves seemingly randomly at times... We will keep our eyes open for similar issues :)

**Pull request merged**
