### PR TITLE
Fix demo links on readme

### PR DESCRIPTION
**Pull request by x4e**
Remove demos that are no longer existant and fix links of existing ones

### CODE REVIEW

**Comment by zeroeightysix** [comment]
LGTM. The removed links already were annotated with warnings though, so I'm not sure if elect wants these gone.

**Comment by cookiedragon234** [comment]
@elect86 would you like me to add back the non existent links?

**Comment by elect86** [comment]
Hey, 

sorry I was in holiday :swimmer:

thanks for the fix

I think it might be useful to leave the links to the jogl and vk backend in order to let people who may be interested in this that there is the possibility to pick them up and work together to make them functional again, what do you think guys?

**Comment by elect86** [comment]
I merged anyway, thanks for the PR!

**Pull request merged**
